# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we're using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install FISH
# add `/usr/local/bin/fish` to `/etc/shells` and run `chsh -s /usr/local/bin/fish` 
install --HEAD fish

# Install GNU core utilities (those that come with OS X are outdated)
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
# Make sure fish can see all these tools
install coreutils

# Install more recent version of some OS X tools
install vim
install homebrew/dupes/grep --default-names

# Install other useful binaries
install git
install tmux
install wget

# Remove outdated versions from the cellar
cleanup
